cc_binary(
    name = "read_file",
    srcs = ["read_file.cc"],
    deps = ["//base/file"],
)

cc_binary(
    name = "rm_tree",
    srcs = [
        "rm_tree.cc"
    ],
    deps = [
        "//base/file",
        "//base/strings",
        "//third_party:glog",
    ],
)

cc_binary(
    name = "current_time",
    srcs = [
        "current_time.cc",
    ],
    deps = [
        "//base/time",
    ],
)
