cc_library(
    name = "terminal",
    hdrs = [
        "scoped_noncanonical_terminal.h",
    ],
    srcs = [
        "scoped_noncanonical_terminal.cc",
    ],
    visibility = ["//visibility:public"],
)