config_setting(
    name = "linux_x64",
    values = {"cpu": "k8"},
    visibility = ["//visibility:public"],
)

config_setting(
    name = "linux_x86",
    values = {"cpu": "piii"},
    visibility = ["//visibility:public"],
)

config_setting(
    name = "darwin",
    values = {"cpu": "darwin"},
    visibility = ["//visibility:public"],
)

config_setting(
    name = "mingw_x64",
    values = {"cpu": "x64_windows"},
    visibility = ["//visibility:public"],
)
