cc_library(
    name = "time",
    srcs = [
        "current_time.cc",
        "time_stamp_counter.cc",
    ],
    hdrs = [
        "current_time.h",
        "time_stamp_counter.h",
    ],
    visibility = [
        "//visibility:public",
    ],
)
