cc_library(
    name = "base",
    srcs = [
        "socket.cc",
    ],
    hdrs = [
        "socket.h",
        "socket_descriptor.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "//base",
        "//third_party:glog",
    ],
)
